version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST='18.224.109.231' # Endere√ßo do banco de dados existente na EC2
      - DB_USER=postgres
      - DB_PASSWORD=12345678
      - DB_NAME=postgres
    ports:
      - '3000:3000'
